### ISSUE TITLE
Integrate Ego into ICGC Portal

### ISSUE THREAD

**Issue by Fgerthoffert** [icgc-dcc/roadmap#2]
- [ ] Finish Ego  (overture-stack/ego#188)
- [ ] Finish Daco2Ego (https://github.com/icgc-dcc/roadmap/issues/7)
- [ ] QA environment setup (https://github.com/icgc-dcc/roadmap/issues/9)
- [ ] Add remaining functions for Ego Admin UI
   - [ ] Add policies and assign permissions to users/groups  
   - [ ] List and revoke user tokens
- [ ] Portal changes & token management  
     - [ ] UI changes for login 
     - [x] Additional endpoints to integrate with Portal UI
     - [ ] Set up all redirects and API calls to EGO

https://docs.google.com/document/d/1hEdSoYUF5FKK4vCYAqT2ug670Kf0gppiEU14M4tWsfI/edit
