### ISSUE TITLE
Daco2Ego service

### ISSUE THREAD

**Issue by alekspejovic** [icgc-dcc/roadmap#7]
Syncs Ego with DACO list of approved users. To be integrated into ICGC. 

- [x] Unpack and decrypt file content for reading (https://github.com/icgc-dcc/Daco2Ego/issues/1)
- [ ] Full sync of Ego users and their permissions (https://github.com/icgc-dcc/Daco2Ego/issues/3)
- [ ] Write test for different scenarios (https://github.com/icgc-dcc/Daco2Ego/issues/5)
- [ ] Authorization with Ego using client credentials flow (https://github.com/icgc-dcc/Daco2Ego/issues/2)
- [ ] Generate report on state changes (https://github.com/icgc-dcc/Daco2Ego/issues/4)
- [ ] Notifications in case of downtime or other issues with WebDev files or service (https://github.com/icgc-dcc/Daco2Ego/issues/6)
